services:
  postgres:
    container_name: "postgres"
    image: postgres:16
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./scripts/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./postgres/logs:/var/log/postgresql  # Ensure logs are directed here in the PostgreSQL config
    env_file:
      - .env
    ports:
      - "5432:5432"
    mem_limit: 512m
    networks:
      ig-network:
        aliases:
          - postgres_host

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./log:/app/log
      - ./src/service/recommendation/ratings_with_id32.csv:/data/ratings_with_id32.csv
    mem_limit: 1024m
    networks:
      ig-network:
        aliases:
          - backend_host
networks:
  ig-network:
    name: int-net
    driver: bridge
    ipam:
      driver: default

volumes:
  db_data: { }
  log: { }
  postgres: { }

