from enum import Enum


class Countries(Enum):
    SPAIN = 'es'
    UNITED_STATES = 'us'
    FRANCE = 'fr'
    GERMANY = 'de'
    ITALY = 'it'
    PORTUGAL = 'pt'
    UNITED_KINGDOM = 'uk'
    JAPAN = 'jp'
    CHINA = 'cn'
    RUSSIA = 'ru'
    BRAZIL = 'br'
    ARGENTINA = 'ar'
    MEXICO = 'mx'
    CANADA = 'ca'
    AUSTRALIA = 'au'
    NEW_ZEALAND = 'nz'
    SOUTH_AFRICA = 'za'
    INDIA = 'in'
    PAKISTAN = 'pk'
    INDONESIA = 'id'
    PHILIPPINES = 'ph'
    SINGAPORE = 'sg'
    MALAYSIA = 'my'
    THAILAND = 'th'
    VIETNAM = 'vn'
    SOUTH_KOREA = 'kr'
    TAIWAN = 'tw'
    HONG_KONG = 'hk'
    MACAU = 'mo'
    SAUDI_ARABIA = 'sa'
    UNITED_ARAB_EMIRATES = 'ae'