"""add image key

Revision ID: 0c4f98a4f3b2
Revises: 8a3ff927cb93
Create Date: 2025-06-04 19:02:12.776614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4f98a4f3b2'
down_revision: Union[str, None] = '8a3ff927cb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('image_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'image_key')
    # ### end Alembic commands ###
