"""add chat_recommended option

Revision ID: 23767fadfe5c
Revises: 6f26d2f269a1
Create Date: 2025-07-01 21:14:48.319869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23767fadfe5c'
down_revision: Union[str, None] = '6f26d2f269a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implicit_data', sa.Column('chat_recommended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('implicit_data', 'chat_recommended')
    # ### end Alembic commands ###
