"""fix entity

Revision ID: 38b718272db4
Revises: 6a8aefbf3a7d
Create Date: 2025-03-30 16:12:50.939318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b718272db4'
down_revision: Union[str, None] = '6a8aefbf3a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_provider', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'watch_provider', 'entity', ['entity_id'], ['entity_id'], ondelete='CASCADE')
    op.drop_column('watch_provider', 'provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_provider', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'watch_provider', type_='foreignkey')
    op.drop_column('watch_provider', 'entity_id')
    # ### end Alembic commands ###
