"""calculated rating

Revision ID: 463b03191f1b
Revises: e8252882cd18
Create Date: 2025-04-27 18:20:50.211627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463b03191f1b'
down_revision: Union[str, None] = 'e8252882cd18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculated_rating',
    sa.Column('calculated_rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_date', sa.Date, nullable=True),
    sa.Column('updated_date', sa.Date, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calculated_rating_id')
    )
    op.drop_column('user_post_info', 'calculated_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post_info', sa.Column('calculated_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_table('calculated_rating')
    # ### end Alembic commands ###
