"""change to datetime

Revision ID: 8a3ff927cb93
Revises: 8df79f4ed811
Create Date: 2025-05-18 15:40:56.045202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3ff927cb93'
down_revision: Union[str, None] = '8df79f4ed811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history', 'created_date',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history', 'created_date',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
