"""addd chat id to chat history

Revision ID: 8df79f4ed811
Revises: 463b03191f1b
Create Date: 2025-05-18 14:28:44.409516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df79f4ed811'
down_revision: Union[str, None] = '463b03191f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('chat_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'chat_id')
    # ### end Alembic commands ###
