"""name

Revision ID: bde76fab663c
Revises: 0578038e59a8
Create Date: 2025-03-10 21:32:23.084585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde76fab663c'
down_revision: Union[str, None] = '0578038e59a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_history_user_id_fkey', 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('implicit_data_user_id_fkey', 'implicit_data', type_='foreignkey')
    op.drop_constraint('implicit_data_post_id_fkey', 'implicit_data', type_='foreignkey')
    op.create_foreign_key(None, 'implicit_data', 'post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'implicit_data', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('playlist_user_id_fkey', 'playlist', type_='foreignkey')
    op.create_foreign_key(None, 'playlist', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('playlist_item_playlist_id_fkey', 'playlist_item', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_item', 'playlist', ['playlist_id'], ['playlist_id'], ondelete='CASCADE')
    op.add_column('post', sa.Column('comments', sa.Integer(), nullable=True))
    op.drop_constraint('saved_playlist_user_id_fkey', 'saved_playlist', type_='foreignkey')
    op.drop_constraint('saved_playlist_playlist_id_fkey', 'saved_playlist', type_='foreignkey')
    op.create_foreign_key(None, 'saved_playlist', 'playlist', ['playlist_id'], ['playlist_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'saved_playlist', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('created_date', sa.Date, nullable=True))
    op.create_unique_constraint(None, 'user', ['uid'])
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_constraint('user_post_info_user_id_fkey', 'user_post_info', type_='foreignkey')
    op.drop_constraint('user_post_info_post_id_fkey', 'user_post_info', type_='foreignkey')
    op.create_foreign_key(None, 'user_post_info', 'post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_post_info', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_post_info', type_='foreignkey')
    op.drop_constraint(None, 'user_post_info', type_='foreignkey')
    op.create_foreign_key('user_post_info_post_id_fkey', 'user_post_info', 'post', ['post_id'], ['post_id'])
    op.create_foreign_key('user_post_info_user_id_fkey', 'user_post_info', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'created_date')
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'saved_playlist', type_='foreignkey')
    op.drop_constraint(None, 'saved_playlist', type_='foreignkey')
    op.create_foreign_key('saved_playlist_playlist_id_fkey', 'saved_playlist', 'playlist', ['playlist_id'], ['playlist_id'])
    op.create_foreign_key('saved_playlist_user_id_fkey', 'saved_playlist', 'user', ['user_id'], ['user_id'])
    op.drop_column('post', 'comments')
    op.drop_constraint(None, 'playlist_item', type_='foreignkey')
    op.create_foreign_key('playlist_item_playlist_id_fkey', 'playlist_item', 'playlist', ['playlist_id'], ['playlist_id'])
    op.drop_constraint(None, 'playlist', type_='foreignkey')
    op.create_foreign_key('playlist_user_id_fkey', 'playlist', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'implicit_data', type_='foreignkey')
    op.drop_constraint(None, 'implicit_data', type_='foreignkey')
    op.create_foreign_key('implicit_data_post_id_fkey', 'implicit_data', 'post', ['post_id'], ['post_id'])
    op.create_foreign_key('implicit_data_user_id_fkey', 'implicit_data', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'post', ['post_id'], ['post_id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key('chat_history_user_id_fkey', 'chat_history', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
