"""users new attrs

Revision ID: d590c50432ff
Revises: 
Create Date: 2025-01-23 18:45:34.747830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd590c50432ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('user',
                    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('uid', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('country', sa.String(), nullable=True),
                    sa.Column('new', sa.Boolean(), nullable=True),
                    sa.Column('sex', sa.String(), nullable=True),
                    sa.Column('language', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
