"""users new attrs

Revision ID: d590c50432ff
Revises: 
Create Date: 2025-01-23 18:45:34.747830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd590c50432ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(), nullable=True))
    op.add_column('user', sa.Column('new', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('user', sa.Column('language', sa.String(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('user', 'enabled')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'username')
    op.drop_column('user', 'language')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'new')
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
