"""comments primary key

Revision ID: e8252882cd18
Revises: 748b26710b54
Create Date: 2025-03-31 13:58:09.442194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8252882cd18'
down_revision: Union[str, None] = '748b26710b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('comments_pkey', 'comments', type_='primary')
    op.create_primary_key('comments_pkey', 'comments', ['comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_id')
    op.drop_constraint('comments_pkey', 'comments', type_='primary')
    op.create_primary_key('comments_pkey', 'comments', ['user_id', 'post_id'])
    # ### end Alembic commands ###
